var five = 5;
var ten = 10;
console.log("Test 1: five is equal to 5?");
console.log(five == 5);
console.log("\nTest 2: ten is equal to 10?");
console.log(ten == 10);
console.log("\nTest 3: five is not equal to 10");
console.log(five != 10);
console.log("\nTest 4: ten is not equal to 5");
console.log(ten != 5);
console.log("\nTest 5: five is smaller than 10");
console.log(five < 10);
console.log("\nTest 6: ten is smaller than 5");
console.log(ten < 5);
console.log("\nTest 7: five is equal to 10?");
console.log(five == 10);
console.log("\nTest 8: ten is not equal to 10");
console.log(ten != 10);
console.log("\nTest 9: five is greater than 10");
console.log(five > 10);
console.log("\nTest 6: hundred is smaller than 50");
console.log(100 < 50);
